In [1]:
import pandas as pd
from datetime import datetime, timedelta



with open('setup.py') as f:
    code = f.read()
exec(code)
run_sql("use hoodalgo_db")





#EXECUTE in MODUELS/ FUNCTIONS -  MAKES SHARED NAMESPACE
############################################################
with open('functions.py') as f:
    code = f.read()
exec(code)
############################################################

✅ Deane’s MySQL Connector V39 — has query_value function
Imported Selenium engine -- v14
📦 Switched default DB to: new_algo_db
📦 Switched default DB to: hoodalgo_db
functions read in

/Users/deanemarks/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

In [20]:
#run_sql("select * from ")

total_scrapes_df = run_sql("""
SELECT scraped_at, COUNT(*) as row_count
FROM robinhood_fundamentals
WHERE scraped_at >= CURDATE()
GROUP BY scraped_at
ORDER BY scraped_at DESC
""").to_df()
total_scrapes_df

           scraped_at  row_count
0 2026-05-05 09:42:39       4210
1 2026-05-05 09:29:43       4210
2 2026-05-05 09:22:31       4210
3 2026-05-05 09:18:58       4210
4 2026-05-05 09:01:08       4210

In [22]:
run_sql("""
SELECT 
    t1.ticker,

    t1.volume,
    t2.volume,

    (t1.volume - t2.volume) AS volume_delta,

    (t1.volume - t2.volume) / t1.average_volume_30_days AS rel_volume_delta,

    t1.open,
    t1.high,
    t1.low,

    ((t1.high - t1.low) / t1.open) AS range_pct,

    t1.market_cap

FROM robinhood_fundamentals t1

JOIN robinhood_fundamentals t2
    ON t1.ticker = t2.ticker

WHERE 
    t1.scraped_at = (SELECT MAX(scraped_at) FROM robinhood_fundamentals)
    AND t2.scraped_at = (
        SELECT MAX(scraped_at)
        FROM robinhood_fundamentals
        WHERE scraped_at < (SELECT MAX(scraped_at) FROM robinhood_fundamentals)
    )

ORDER BY rel_volume_delta DESC
LIMIT 100
""")

,ticker,volume,volume_delta,rel_volume_delta,open,high,low,range_pct,market_cap
0,LPRO,326701,320838,0.557114,1.8,1.82,1.715,0.058333,208062000
1,AIOS,1613130,167161,0.488252,16.0,31.78,16.0,0.98625,101409000
2,BLZE,27742000,318168,0.454354,7.46,8.4199,7.13,0.172909,434523000
3,INMB,89738,108899,0.439374,1.5,1.55,1.4601,0.059933,39745000
4,DGXX,81041900,977416,0.429565,5.34,5.62,4.71,0.170412,359522000
...,...,...,...,...,...,...,...,...,...
95,NGEN,80616,10593,0.049089,3.67,3.7497,3.55,0.054414,292565000
96,CRON,334250,93734,0.048807,2.65,2.7,2.635,0.024528,1006210000
97,ONT,41275,14298,0.048356,21.8,22.43,21.5,0.042661,798629000
98,SONO,1808860,57401,0.048268,14.9,15.03,12.83,0.147651,1636620000
99,PICS,45621,17220,0.048207,11.75,11.9,11.51,0.033191,1516170000