In [1]:

#################################################################################################
#-Child level - DB setup (Feb 25 - V1)
#################################################################################################

import os

def run_file(filename):
    d = os.getcwd()
    f = None

    while not f:
        for r, _, files in os.walk(d):
            if filename in files:
                f = os.path.join(r, filename)
                break
        if f or os.path.dirname(d) == d:
            break
        d = os.path.dirname(d)

    if not f:
        raise FileNotFoundError(f"{filename} not found")

    exec(open(f).read(), globals())



try:
    master_dir
except NameError:
    master_dir = False



#Child Dir System Setup -- Use for Testing
if not master_dir:
    run_file("mysqlconnector.py")
    run_file("selenium_setup.py")


    
    #Define the Db you are using
    print('')
    run_sql('use new_algo_db ')
    print('')

    
    #get a test_ticker_list to test in your script
    #probs hardcode this actually so it dosent break
    #job for another day
    ###########################################################
    df = run_sql("""
    select * from scraper__wsj_gainers;
    """).to_df()
    test_ticker_list = df['ticker'].to_list()
    test_ticker_list = list(set(test_ticker_list))[:30]
    ###########################################################



    
    print('Child level system setup success ')
    print("\nNOTE: use test_ticker_list to test function")

    

#################################################################################################

✅ Deane’s MySQL Connector V39 — has query_value function
Imported Selenium engine -- v9

📦 Switched default DB to: new_algo_db

Child level system setup success

NOTE: use test_ticker_list to test function

/Users/deanemarks/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

In [8]:
run_sql("""


show databases;
use new_algo_db;




""")

📦 Switched default DB to: new_algo_db

       Tables_in_new_algo_db
0         admin__algo_status
1                       news
2     robinhood_fundamentals
3            robinhood_price
4      scraper__trading_view
5       scraper__wsj_gainers
6       ticker_universe__all
7  ticker_universe__filtered

In [22]:
run_sql("""


CREATE TABLE admin__Algo__scraper_inputs (

    id INT AUTO_INCREMENT PRIMARY KEY,

    algo VARCHAR(100) NOT NULL UNIQUE,

    scraper_stocktwits TINYINT(1) NOT NULL DEFAULT 0,
    scraper_wsj TINYINT(1) NOT NULL DEFAULT 0,
    scraper_tradingview TINYINT(1) NOT NULL DEFAULT 0,
    scraper_benzinga TINYINT(1) NOT NULL DEFAULT 0,
    scraper_yahoo TINYINT(1) NOT NULL DEFAULT 0,
    scraper_etf_universe TINYINT(1) NOT NULL DEFAULT 0,

    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP

);

show tables

""")

          Tables_in_new_algo_db
0         admin__algo__schedule
1   admin__Algo__scraper_inputs
2     admin__algo__trade_window
3            admin__algo_status
4                          news
5        robinhood_fundamentals
6               robinhood_price
7         scraper__trading_view
8          scraper__wsj_gainers
9          ticker_universe__all
10    ticker_universe__filtered

In [63]:

algo_name = 'Alpha'


status = run_sql(f"""select status from admin__algo_status where algo_name = '{algo_name}'""").to_df()['status'][0]
status

'test'

In [71]:
algo = 'Alpha'


run_sql(f"""




select * from admin__Algo__scraper_inputs where algo = '{algo}' ;



""")

,id,algo,scraper_stocktwits,scraper_wsj,scraper_tradingview,scraper_benzinga,scraper_yahoo,scraper_etf_universe,updated_at
0,1,Alpha,1,1,1,1,0,0,2026-03-01 14:48:46